version: "3"

services:
  agroofdb:
    image: postgres:latest
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data

  agroofapi:
    build:
      context: .
    depends_on:
      - agroofdb  
    volumes:
      - .:/app
    command: /app/scripts/start_dev_server.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    ports:
      - ${API_PORT}:7071
    env_file:
      - .env
      
volumes:
  db-data: