# Generated by Django 3.2 on 2021-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom')),
                ('latin_name', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom latin')),
                ('family', models.CharField(blank=True, default='', max_length=250, verbose_name='Famille')),
                ('continentality', models.IntegerField(blank=True, verbose_name='Contiinentalité')),
                ('humidity_a', models.IntegerField(blank=True, verbose_name='Humidité_a')),
                ('light', models.IntegerField(blank=True, verbose_name='Lumière')),
                ('ph', models.IntegerField(blank=True, verbose_name='Ph')),
                ('texture', models.IntegerField(blank=True, verbose_name='Texture')),
                ('humidity', models.IntegerField(blank=True, verbose_name='Humidité')),
                ('salinity', models.IntegerField(blank=True, verbose_name='Salinité')),
                ('organic_material', models.IntegerField(blank=True, verbose_name='Matière organique')),
                ('name_img', models.CharField(blank=True, default='', max_length=250, verbose_name='Nom img')),
            ],
        ),
    ]
