# Generated by Django 3.2 on 2021-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_rename_job_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humidité'),
        ),
    ]
