# Generated by Django 3.2 on 2021-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_auto_20210504_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='continentality',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='humidity_a',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='light',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='organic_material',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='salinity',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='texture',
        ),
        migrations.AddField(
            model_name='tree',
            name='continentality_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contiinentalité max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='continentality_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contiinentalité min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='humidity_a_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humidité_a max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='humidity_a_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humidité_a min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='humidity_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humidité max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='humidity_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humidité min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='light_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lumière max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='light_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lumière min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='organic_material_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matière organique max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='organic_material_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matière organique min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='ph_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ph max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='ph_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ph min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='salinity_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salinité max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='salinity_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salinité min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='texture_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Texture max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='texture_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Texture min'),
        ),
    ]
