# Generated by Django 3.2 on 2021-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_auto_20210525_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='nutrient_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nutriment max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='nutrient_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nutriment min'),
        ),
        migrations.AddField(
            model_name='tree',
            name='temperature_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Température max'),
        ),
        migrations.AddField(
            model_name='tree',
            name='temperature_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Température min'),
        ),
    ]
